[43기 장지원][ADD] db schema 작성
wecode-bootcamp-korea/43-2nd-finding-maewha-backend pull request #2
Opened 2023-03-27 11:30 UTC by yucori

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- db 스키마 작성

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- db 스키마 작성

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![스크린샷 2023-03-27 오후 8 29 32](https://user-images.githubusercontent.com/110710238/227929212-71106115-59c6-4a94-9a6b-131b7e998a3e.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-27 12:06 UTC, kyeongraekim requested changes

2023-03-27 12:06 UTC, kyeongraekim commented on db/migrations/20230327111717_create_table_basic_info.sql
> +CREATE TABLE basic_info(
- 테이블명, 칼럼명에는 약어가 아닌 영어의 원어를 꼭 풀어서 쓸 수 있도록 습관화해주세요!~

2023-03-27 12:06 UTC, kyeongraekim commented on db/migrations/20230327111717_create_table_basic_info.sql
> +CREATE TABLE basic_info(
- 그리고 basic_info는 너무 포괄적인 표현인 것 같습니다. 예를들어 place_basic_information 과 같이 어떤 데이터 리소스에 대한 기본 정보 그리고 아래는 추가 정보인지 명시해주세요!

2023-03-27 12:06 UTC, kyeongraekim commented on db/migrations/20230327111643_create_table_places.sql
> +	social_id VARCHAR(3000),
- 혹시 이 social_id에는 어떤 데이터 값이 들어올 예정인가요? 한 번 공유해주세요!

2023-03-27 12:06 UTC, kyeongraekim commented on db/migrations/20230327112215_create_table_review_likes.sql
> +);
- 한명의 유저가 동일한 상품에 좋아요를 누를 수 없게 unique 제한을 걸어둘 필요가 있어 보이네요!

2023-03-27 12:06 UTC, kyeongraekim commented on db/migrations/20230327112620_create_table_liked_places.sql
> +-- migrate:down
- 이곳도 unique 제한을 고려해보세요!

2023-03-28 01:32 UTC, yucori commented on db/migrations/20230327111643_create_table_places.sql
> +	social_id VARCHAR(3000),
카카오에 등록되어있는 장소의 경우에는 카카오에서의 장소id도 저장해두려고 합니다!

2023-03-28 03:13 UTC, kyeongraekim approved these changes
LGTM!~

2023-03-28 03:14 UTC, merged